# This is a basic workflow to help you get started with Actions

name: first_workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      number1:
        description: 'First Number'
        default: '0'
        required: true
      number2:
        description: 'Second Number'
        default: '0'
        required: true
      
      
env: 
  cloud: aws-cloud
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_numbers:
    
  # This workflow contains a single job called "build"
#  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Add Numbers
        id: sum
        run: echo "::set-output name=sum::$((${{ inputs.number1 }} + ${{ inputs.number2 }}))"

      - name: Discplay Sum
        run: echo "The sum of ${{ inputs.number1}} and ${{ inputs.number2}} is ${{ steps.sum.outputs.sum }}"
